pipeline {
  agent any
  stages {
      stage('Install Requirements') {
          steps {
            script {
              echo 'Stage 1'
              bat '''
                pip install behave
                pip install allure-behave
              '''
            }
          }
      }
      stage('Import TCs') {
          steps {
            script {
              echo 'Stage 2'
              bat '''
				cd Utilities
				python testcasesimport.py
			  '''
            }
          }
      }
      stage('Run TCs') {
          steps {
            script {
              echo 'Stage 2'
              bat '''
                behave -f allure_behave.formatter:AllureFormatter -o reports
                allure serve reports
              '''
            }
          }
      }
      stage('Generate Reports'){
        steps{
            script {
                  allure([
                    includeProperties: false,
                    jdk: '',
                    properties: [],
                    reportBuildPolicy: 'ALWAYS',
                    results: [[path: 'target/allure-results']]
                  ])
            }
        }
      }
  }
}